name: multi-kernel-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - bash_kernel
  - xeus-cling
  - nodejs
  - r-base
  - r-irkernel
  - julia
  - octave
  - openjdk
  - rust
  - go
  - dotnet-sdk
  - ghc                 # Haskell compiler
  - stack               # Haskell toolchain
  - pip:
      - ijavascript
      - octave_kernel
