name: multi-kernel-env
channels:
  - conda-forge
  - defaults
  - r
dependencies:
  - python=3.10
  - pip
  - nodejs
  - bash_kernel
  - r-base
  - r-irkernel
  - julia
  - octave
  - pip:
      - ijavascript
      - octave_kernel
