name: multi-kernel-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - bash_kernel
  - xeus-cling  # C++11, C++14, C++17 kernels
  - nodejs
  - r-base
  - r-irkernel
  - julia
  - octave
  - openjdk
  - pip:
      - ijavascript
      - octave_kernel
