name: multi-kernel-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - bash_kernel
  - xeus-cling  # C++
  - nodejs
  - r-base
  - r-irkernel
  - julia
  - octave
  - openjdk
  - rust
  - go
  - lua
  - php
  - perl
  - haskell
  - swift
  - kotlin
  - pip:
      - octave_kernel
